export const chatsData = [
  {
    id: 1,
    chatName: "Вася",
    //сделать хелпер для инициалов
    initials: "ВС",
    avatar: "https://i.pravatar.cc/300?img=1",
    lastMessage: "Hello. Тут я напишу длинный текст для того чтобы проверить как работает перенос текста.",
    lastMessageTime: "10:00",
    incoming: true,
    unreadMessagesCount: 0,
    active: true,
  },
  {
    id: 2,
    chatName: "Петя",
    initials: "ПТ",
    avatar: "",
    lastMessage: "Hi",
    lastMessageTime: "11:00",
    incoming: false,
    unreadMessagesCount: 2,
    active: false,
  },
  {
    id: 3,
    chatName: "Коля",
    initials: "КЛ",
    avatar: "https://i.pravatar.cc/300?img=3",
    lastMessage: "Yo",
    lastMessageTime: "12:00",
    incoming: true,
    unreadMessagesCount: 0,
    active: false,
  },
];
export const emptyChatsData = [
  {
    id: 1,
    chatName: "Вася",
    //сделать хелпер для инициалов
    initials: "ВС",
    avatar: "https://i.pravatar.cc/300?img=1",
    lastMessage: "Hello. Тут я напишу длинный текст для того чтобы проверить как работает перенос текста.",
    lastMessageTime: "10:00",
    incoming: true,
    unreadMessagesCount: 0,
    active: false,
  },
  {
    id: 2,
    chatName: "Петя",
    initials: "ПТ",
    avatar: "",
    lastMessage: "Hi",
    lastMessageTime: "11:00",
    incoming: false,
    unreadMessagesCount: 2,
    active: false,
  },
  {
    id: 3,
    chatName: "Коля",
    initials: "КЛ",
    avatar: "https://i.pravatar.cc/300?img=3",
    lastMessage: "Yo",
    lastMessageTime: "12:00",
    incoming: true,
    unreadMessagesCount: 0,
    active: false,
  },
];
